import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('data/kidney.csv')

data_ill = data[data['class'] == 'ckd']

data_healthy = data[data['class'] == 'notckd']

data.head(5)

data.shape

data.describe()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('Age histogram')
ax1.hist(data['age'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['age'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['age'], bins=20)
ax3.set_title('Healthy')
fig.show()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('BP histogram')
ax1.hist(data['bp'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['bp'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['bp'], bins=20)
ax3.set_title('Healthy')
fig.show()
data['bp'].unique()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('SG histogram')
ax1.hist(data['sg'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['sg'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['sg'], bins=20)
ax3.set_title('Healthy')
fig.show()
data['sg'].unique()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('AL histogram')
ax1.hist(data['al'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['al'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['al'], bins=20)
ax3.set_title('Healthy')
data['al'].unique()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('SU histogram')
ax1.hist(data['su'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['su'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['su'], bins=20)
ax3.set_title('Healthy')
data['su'].unique()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('BGR histogram')
ax1.hist(data['bgr'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['bgr'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['bgr'], bins=20)
ax3.set_title('Healthy')
plt.show()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('BU histogram')
ax1.hist(data['bu'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['bu'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['bu'], bins=20)
ax3.set_title('Healthy')
plt.show()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('SC histogram')
ax1.hist(data['sc'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['sc'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['sc'], bins=20)
ax3.set_title('Healthy')
data['sc'].unique()
data_healthy['sc'].max()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('SOD histogram')
ax1.hist(data['sod'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['sod'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['sod'], bins=20)
ax3.set_title('Healthy')

data_healthy['sod'].min()
data['sod'].unique()


fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('POT histogram')
ax1.hist(data['pot'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['pot'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['pot'], bins=20)
ax3.set_title('Healthy')
data['pot'].unique()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('hemo histogram')
ax1.hist(data['hemo'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['hemo'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['hemo'], bins=20)
ax3.set_title('Healthy')
data['hemo'].unique()
data_healthy['hemo'].min()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('PCV histogram')
ax1.hist(data['pcv'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['pcv'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['pcv'], bins=20)
ax3.set_title('Healthy')
data_healthy['pcv'].min()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('WBCC histogram')
ax1.hist(data['wbcc'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['wbcc'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['wbcc'], bins=20)
ax3.set_title('Healthy')
data_healthy['wbcc'].max()
data['wbcc'].unique()

fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(15,7))
fig.suptitle('RBCC histogram')
ax1.hist(data['rbcc'], bins=20)
ax1.set_title('All')
ax2.hist(data_ill['rbcc'], bins=20)
ax2.set_title('Ill')
ax3.hist(data_healthy['rbcc'], bins=20)
ax3.set_title('Healthy')

data['rbcc'].unique()
data_healthy['rbcc'].min()
